obj-$(CONFIG_HUAWEI_THP) += thp.o
thp-objs += huawei_thp_attr.o huawei_thp_core.o huawei_thp_mt_wrapper.o
obj-$(CONFIG_HUAWEI_THP_NOVATECH) += novatech_thp.o
obj-$(CONFIG_JDI_HOST_TS_KIT) += bu21150_thp.o
EXTRA_CFLAGS += -Idrivers/hisi/tzdriver
EXTRA_CFLAGS += -Idrivers/tzdriver
EXTRA_CFLAGS += -Idrivers/devkit/lcdkit/core/common

