
obj-$(CONFIG_LCDKIT_DRIVER) += lcdkit_fb_util_qcom.o
obj-$(CONFIG_LCDKIT_DRIVER) += lcdkit_panel_adaptor_qcom.o
obj-$(CONFIG_LCDKIT_DRIVER) += lcdkit_debug_msm.o
obj-$(CONFIG_LCDKIT_DRIVER) += lcdkit_dsm.o
obj-$(CONFIG_LCDKIT_DRIVER) += lcdkit_bias_bl_utility.o
EXTRA_CFLAGS += -Idrivers/devkit/lcdkit/include	\
                -Idrivers/devkit/lcdkit/core/common/qcom \
                -Idrivers/video/msm/mdss	\
                -Iinclude